### ISSUE TITLE
Error to post feed with dialog

### ISSUE THREAD

**Issue by bagusflyer** [sromku/android-simple-facebook#285]
I got the following error message when I'm trying to post feed with dialog:

> ERROR: Failed to share by using native dialog

It crashes on MainActivity at:

    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        mSimpleFacebook.onActivityResult(this, requestCode, resultCode, data);
    }

The full error message:

>
01-21 05:36:15.276    2108-2108/? E/com.sromku.simple.fb.actions.PublishFeedDialogAction﹕ -----
01-21 05:36:15.276    2108-2108/? E/com.sromku.simple.fb.actions.PublishFeedDialogAction﹕ ERROR: Failed to share by using native dialog
    com.facebook.FacebookException: Error publishing message
            at com.facebook.internal.NativeProtocol.getExceptionFromErrorData(NativeProtocol.java:624)
            at com.facebook.widget.FacebookDialog.handleActivityResult(FacebookDialog.java:387)
            at com.facebook.UiLifecycleHelper.handleFacebookDialogActivityResult(UiLifecycleHelper.java:301)
            at com.facebook.UiLifecycleHelper.onActivityResult(UiLifecycleHelper.java:165)
            at com.sromku.simple.fb.SessionManager.onActivityResult(SessionManager.java:378)
            at com.sromku.simple.fb.SimpleFacebook.onActivityResult(SimpleFacebook.java:1964)
            at com.wowtv.fbpost.MainActivity.onActivityResult(MainActivity.java:65)
            at android.app.Activity.dispatchActivityResult(Activity.java:5322)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3363)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3410)
            at android.app.ActivityThread.access$1100(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
01-21 05:36:15.276    2108-2108/? E/com.sromku.simple.fb.actions.PublishFeedDialogAction﹕ java.lang.Throwable
            at com.sromku.simple.fb.utils.Logger.getStackTrace(Logger.java:69)
            at com.sromku.simple.fb.utils.Logger.logError(Logger.java:55)
            at com.sromku.simple.fb.actions.PublishFeedDialogAction$1.onError(PublishFeedDialogAction.java:52)
            at com.facebook.widget.FacebookDialog.handleActivityResult(FacebookDialog.java:389)
            at com.facebook.UiLifecycleHelper.handleFacebookDialogActivityResult(UiLifecycleHelper.java:301)
            at com.facebook.UiLifecycleHelper.onActivityResult(UiLifecycleHelper.java:165)
            at com.sromku.simple.fb.SessionManager.onActivityResult(SessionManager.java:378)
            at com.sromku.simple.fb.SimpleFacebook.onActivityResult(SimpleFacebook.java:1964)
            at com.wowtv.fbpost.MainActivity.onActivityResult(MainActivity.java:65)
            at android.app.Activity.dispatchActivityResult(Activity.java:5322)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3363)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3410)
            at android.app.ActivityThread.access$1100(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
01-21 05:36:23.476    2108-2108/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64207, result=0, data=Intent { (has extras) }} to activity {com.wowtv.fbpost/com.wowtv.fbpost.MainActivity}: com.facebook.FacebookException: Attempted to use a Session that was not open.
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3367)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3410)
            at android.app.ActivityThread.access$1100(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: com.facebook.FacebookException: Attempted to use a Session that was not open.
            at com.facebook.widget.WebDialog$BuilderBase.<init>(WebDialog.java:524)
            at com.facebook.widget.WebDialog$FeedDialogBuilder.<init>(WebDialog.java:708)
            at com.sromku.simple.fb.actions.PublishFeedDialogAction.shareWithWebDialog(PublishFeedDialogAction.java:89)
            at com.sromku.simple.fb.actions.PublishFeedDialogAction.access$0(PublishFeedDialogAction.java:88)
            at com.sromku.simple.fb.actions.PublishFeedDialogAction$1.onError(PublishFeedDialogAction.java:56)
            at com.facebook.widget.FacebookDialog.handleActivityResult(FacebookDialog.java:389)
            at com.facebook.UiLifecycleHelper.handleFacebookDialogActivityResult(UiLifecycleHelper.java:301)
            at com.facebook.UiLifecycleHelper.onActivityResult(UiLifecycleHelper.java:165)
            at com.sromku.simple.fb.SessionManager.onActivityResult(SessionManager.java:378)
            at com.sromku.simple.fb.SimpleFacebook.onActivityResult(SimpleFacebook.java:1964)
            at com.wowtv.fbpost.MainActivity.onActivityResult(MainActivity.java:65)
            at android.app.Activity.dispatchActivityResult(Activity.java:5322)
            at android.app.ActivityThread.deliverResults(ActivityThread.java:3363)
            at android.app.ActivityThread.handleSendResult(ActivityThread.java:3410)
            at android.app.ActivityThread.access$1100(ActivityThread.java:141)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:525)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by bagusflyer** [comment]
I think it's keyhash problem.
