### ISSUE TITLE
publish feed doesn't work

### ISSUE THREAD

**Issue by croccio** [sromku/android-simple-facebook#309]
26914-27685/com.facebook.katana W/fb4a(:<default>):BlueServiceQueue﹕ Exception during service
    com.facebook.http.protocol.ApiException: [code] 100 [message]: Unsupported get request. Please read the Graph API documentation at https://developers.facebook.com/docs/graph-api [extra]:
            at com.facebook.http.protocol.ApiResponseChecker.b(ApiResponseChecker.java:104)
            at com.facebook.http.protocol.ApiResponseChecker.a(ApiResponseChecker.java:137)
            at com.facebook.http.protocol.ApiResponseChecker.a(ApiResponseChecker.java:234)
            at com.facebook.http.protocol.ApiResponseChecker.a(ApiResponseChecker.java:185)
            at com.facebook.http.protocol.JsonResponseHandler.a(JsonResponseHandler.java:34)
            at com.facebook.http.protocol.ApiResponseHandler.b(ApiResponseHandler.java:91)
            at com.facebook.http.protocol.ApiResponseHandler.a(ApiResponseHandler.java:54)
            at com.facebook.http.protocol.ApiResponseHandler.handleResponse(ApiResponseHandler.java:29)
            at com.facebook.http.common.FbHttpRequestProcessor.a(FbHttpRequestProcessor.java:768)
            at com.facebook.http.common.FbHttpRequestProcessor.a(FbHttpRequestProcessor.java:245)
            at com.facebook.http.common.FbHttpRequestProcessor.a(FbHttpRequestProcessor.java:177)
            at com.facebook.http.common.FbHttpRequestProcessor.a(FbHttpRequestProcessor.java:359)
            at com.facebook.http.protocol.SingleMethodRunnerImpl.a(SingleMethodRunnerImpl.java:553)
            at com.facebook.http.protocol.SingleMethodRunnerImpl.b(SingleMethodRunnerImpl.java:257)
            at com.facebook.http.protocol.AbstractSingleMethodRunner.a(AbstractSingleMethodRunner.java:20)
            at com.facebook.tools.fieldcount.runtime.SingleMethodRunnerDetours.a(SingleMethodRunnerDetours.java:23)
            at com.facebook.platform.common.server.SimplePlatformOperation.a(SimplePlatformOperation.java:39)
            at com.facebook.platform.common.server.PlatformOperationHandler.a(PlatformOperationHandler.java:59)
            at com.facebook.fbservice.service.BlueServiceQueue.f(BlueServiceQueue.java:391)
            at com.facebook.fbservice.service.BlueServiceQueue.d(BlueServiceQueue.java:63)
            at com.facebook.fbservice.service.BlueServiceQueue$3.run(BlueServiceQueue.java:308)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at com.facebook.common.executors.ListenableScheduledFutureImpl.run(ListenableScheduledFutureImpl.java:60)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by luisestudioalfa** [comment]
Same problem..... Did you find a solution?

**Comment by solutelia** [comment]
Hi, there, 

This mail address is not use any more.

Please send to noah@solutelia.net 

Thanks,
