### ISSUE TITLE
Support Facebook SDK 4.0

### ISSUE THREAD

**Issue by khacanh** [sromku/android-simple-facebook#312]
Stacktrace 

```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/internal/SessionAuthorizationType;
            at com.sromku.simple.fb.Permission$Type.<clinit>(Permission.java:292)
            at com.sromku.simple.fb.Permission.<clinit>(Permission.java:32)
            at com.prism.sen.app.App.<init>(App.java:32)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.Class.newInstance(Class.java:1572)
            at android.app.Instrumentation.newApplication(Instrumentation.java:994)
            at android.app.Instrumentation.newApplication(Instrumentation.java:979)
            at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4491)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.internal.SessionAuthorizationType" on path: DexPathList[[zip file "/data/app/com.prism.sen.app-1/base.apk"],nativeLibraryDirectories=[/data/app/com.prism.sen.app-1/lib/arm, /vendor/lib, /system/lib]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
            at com.sromku.simple.fb.Permission$Type.<clinit>(Permission.java:292)
            at com.sromku.simple.fb.Permission.<clinit>(Permission.java:32)
            at com.prism.sen.app.App.<init>(App.java:32)
            at java.lang.reflect.Constructor.newInstance(Native Method)
            at java.lang.Class.newInstance(Class.java:1572)
            at android.app.Instrumentation.newApplication(Instrumentation.java:994)
            at android.app.Instrumentation.newApplication(Instrumentation.java:979)
            at android.app.LoadedApk.makeApplication(LoadedApk.java:558)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4491)
            at android.app.ActivityThread.access$1500(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
    Suppressed: java.lang.ClassNotFoundException: com.facebook.internal.SessionAuthorizationType
            at java.lang.Class.classForName(Native Method)
            at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
            at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
            ... 19 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by sromku** [comment]
Yep, they changed much stuff there. I will get into updating the lib in the next couple of days. 
@khacanh thanks.

**Comment by stezo** [comment]
@sromku can you give us an estimate about your progress?
Thanks.

**Comment by konigsoft** [comment]
Hi @sromku have you plan to release it on maven too.
I am pretty sure that you are aware that facebook is on gradle so we can use the gradle dependency in your library

**Comment by changyuheng** [comment]
I found another library: [RetroFacebook](https://github.com/yongjhih/RetroFacebook).
It uses annotation to reduce the code and RxJava to control the flow.
Interesting!

**Comment by gkbhardwaj88** [comment]
Hi I have library invite-friend-lib in my project but invite is send and request id also displayed but not received invite on friend. What is problem? I want to now that.
