### ISSUE TITLE
FacebookServiceException trying to publish a story

### ISSUE THREAD

**Issue by anelfdz** [sromku/android-simple-facebook#329]
I'm trying to publish an story and I getting the following exception:

{FacebookServiceException: httpResponseCode: 400, facebookErrorCode: -1, facebookErrorType: null, message: null}
at com.facebook.FacebookRequestError.<init>(FacebookRequestError.java:135)
at com.facebook.FacebookRequestError.<init>(FacebookRequestError.java:197)
at com.facebook.FacebookRequestError.checkResponseAndCreateError(FacebookRequestError.java:442)
at com.facebook.Response.createResponseFromObject(Response.java:424)
at com.facebook.Response.createResponsesFromObject(Response.java:407)
at com.facebook.Response.createResponsesFromString(Response.java:358)
at com.facebook.Response.createResponsesFromStream(Response.java:350)
at com.facebook.Response.fromHttpConnection(Response.java:324)
at com.facebook.Request.executeConnectionAndWait(Request.java:1563)
at com.facebook.Request.executeBatchAndWait(Request.java:1462)
at com.facebook.RequestBatch.executeAndWaitImpl(RequestBatch.java:237)
at com.facebook.RequestBatch.executeAndWait(RequestBatch.java:187)
at com.facebook.RequestAsyncTask.doInBackground(RequestAsyncTask.java:163)
at com.facebook.RequestAsyncTask.doInBackground(RequestAsyncTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)

**Comment by sromku** [comment]
@anelfdz, can you please check the latest version? There is a maven support and you can easily use this lib. You can find it here: https://github.com/sromku/android-simple-facebook#latest-release
And, if it still fails, please describe what have you done so far to post open graph story. Have you created object and action on fb console? This is an example: https://github.com/sromku/android-simple-facebook/wiki/Publish-story
