### ISSUE TITLE
Like Publish crash 

### ISSUE THREAD

**Issue by cabuhatprince** [sromku/android-simple-facebook#335]
I got this error i dont know why :(
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.sromku.simple.fb.SimpleFacebook.publish(java.lang.String, com.sromku.simple.fb.entities.Like, com.sromku.simple.fb.listeners.OnPublishListener)' on a null object reference
            at better.business.solution.parking.MyAdapter$2.onClick(MyAdapter.java:168)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19761)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5253)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

this is my code:

holder.likeButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                Like like_sample = new Like.Builder().build();

                SimpleFacebook.getInstance().publish("59401015751_10154141532515752", like_sample, new OnPublishListener() {

                    @Override
                    public void onException(Throwable throwable) {
                        super.onException(throwable);
                    }

                    @Override
                    public void onFail(String reason) {
                        super.onFail(reason);
                    }

                    @Override
                    public void onThinking() {
                        super.onThinking();
                    }

                    @Override
                    public void onComplete(String response) {
                        super.onComplete(response);
                        Log.e("LIKE","LIKE");
                    }
                });

**Comment by sromku** [comment]
@cabuhatprince It looks like you didn't implemented this line: https://github.com/sromku/android-simple-facebook/wiki/Configuration#1-onresume in your code. Let me know if it helped.

**Comment by cabuhatprince** [comment]
Hi, im done of configuration but if i click the like button in my app it's not coming on onComplete then when i try to see it in  the native facebook like there is none like having done.

**Comment by sromku** [comment]
@cabuhatprince Have you added this line also in your app: https://github.com/sromku/android-simple-facebook/wiki/Configuration#2-override-onactivityresult-method-and-add-this-line ?

**Comment by cabuhatprince** [comment]
When im using it using may fb admin everthing is okay, but when o try to
login different account that's what is happening.
