### ISSUE TITLE
IllegalStateException - OnProfileListener - Expected a string but was BEGIN_OBJECT

### ISSUE THREAD

**Issue by grembek** [sromku/android-simple-facebook#344]
I have an exception thrown each time I use the OnProfileListener. Please find below the stacktrace:

OnProfileListener - onException
    com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 532 path $.education[2].degree
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)
            at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
            at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
            at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
            at com.google.gson.Gson.fromJson(Gson.java:810)
            at com.google.gson.Gson.fromJson(Gson.java:775)
            at com.google.gson.Gson.fromJson(Gson.java:724)
            at com.google.gson.Gson.fromJson(Gson.java:696)
            at com.sromku.simple.fb.utils.JsonUtils.fromJson(JsonUtils.java:67)
            at com.sromku.simple.fb.actions.GetProfileAction.processResponse(GetProfileAction.java:38)
            at com.sromku.simple.fb.actions.GetProfileAction.processResponse(GetProfileAction.java:11)
            at com.sromku.simple.fb.actions.GetAction$1.onCompleted(GetAction.java:48)
            at com.facebook.GraphRequest$5.run(GraphRequest.java:1243)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 532 path $.education[2].degree
            at com.google.gson.stream.JsonReader.nextString(JsonReader.java:837)
            at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:358)
            at com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:346)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
            at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
            at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:81)
            at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:60)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
            at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
            at com.google.gson.Gson.fromJson(Gson.java:810)
            at com.google.gson.Gson.fromJson(Gson.java:775)
            at com.google.gson.Gson.fromJson(Gson.java:724)
            at com.google.gson.Gson.fromJson(Gson.java:696)
            at com.sromku.simple.fb.utils.JsonUtils.fromJson(JsonUtils.java:67)
            at com.sromku.simple.fb.actions.GetProfileAction.processResponse(GetProfileAction.java:38)
            at com.sromku.simple.fb.actions.GetProfileAction.processResponse(GetProfileAction.java:11)
            at com.sromku.simple.fb.actions.GetAction$1.onCompleted(GetAction.java:48)
            at com.facebook.GraphRequest$5.run(GraphRequest.java:1243)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by sromku** [comment]
@grembek to be fixed. Will update you soon

**Comment by grembek** [comment]
@sromku Thanks!

**Comment by sromku** [comment]
With light delay, the fixed was uploaded to jcenter: 4.0.6
